version: "3"

services:
    vc_usuario-backend:
        container_name: vc_usuario-backend
        build: .
        command: npm start
        ports:
            - "8000:8000"
        volumes: 
            - .:/usr/app